//! Git object representations and utilities.

pub mod blob;
pub mod commit;
pub mod signature;
pub mod tag;
pub mod tree;
pub mod types;
pub(crate) mod utils;

use std::{
    fmt::Display,
    io::{BufRead, Read},
    str::FromStr,
};

use sha1::Digest;

use callisto::{
    git_blob, git_commit, git_tag, git_tree, mega_blob, mega_commit, mega_tag, mega_tree, raw_blob,
};

use crate::internal::object::types::ObjectType;
use crate::internal::object::{blob::Blob, commit::Commit, tag::Tag, tree::Tree};
use crate::internal::zlib::stream::inflate::ReadBoxed;
use crate::{errors::GitError, hash::SHA1};

/// Common behaviour shared by all Git objects.
pub trait ObjectTrait: Send + Sync + Display {
    /// Creates a new object from raw bytes and its hash.
    fn from_bytes(data: &[u8], hash: SHA1) -> Result<Self, GitError>
    where
        Self: Sized;

    /// Generate a new object from a [`ReadBoxed`] reader.
    /// The input size is used to pre-allocate the internal buffer.
    fn from_buf_read<R: BufRead>(read: &mut ReadBoxed<R>, size: usize) -> Self
    where
        Self: Sized,
    {
        let mut content: Vec<u8> = Vec::with_capacity(size);
        read.read_to_end(&mut content).unwrap();
        let h = read.hash.clone();
        let hash_str = h.finalize();
        Self::from_bytes(&content, SHA1::from_str(&format!("{hash_str:x}")).unwrap()).unwrap()
    }

    /// Returns the type of the object.
    fn get_type(&self) -> ObjectType;

    /// Returns the size of the object's content in bytes.
    fn get_size(&self) -> usize;

    /// Converts the object into its raw byte representation.
    fn to_data(&self) -> Result<Vec<u8>, GitError>;
}

/// Represents a Git object with its concrete type.
#[derive(PartialEq, Debug, Clone)]
pub enum GitObject {
    /// A commit object.
    Commit(Commit),
    /// A tree object.
    Tree(Tree),
    /// A blob object.
    Blob(Blob),
    /// A tag object.
    Tag(Tag),
}

/// Intermediate representation of Git objects generated by conversions.
#[derive(PartialEq, Debug, Clone)]
pub enum GitObjectModel {
    /// A commit model.
    Commit(git_commit::Model),
    /// A tree model.
    Tree(git_tree::Model),
    /// A blob model paired with raw blob data.
    Blob(git_blob::Model, raw_blob::Model),
    /// A tag model.
    Tag(git_tag::Model),
}

/// Mega's internal representation of Git objects.
pub enum MegaObjectModel {
    /// A commit model.
    Commit(mega_commit::Model),
    /// A tree model.
    Tree(mega_tree::Model),
    /// A blob model paired with raw blob data.
    Blob(mega_blob::Model, raw_blob::Model),
    /// A tag model.
    Tag(mega_tag::Model),
}

impl GitObject {
    /// Converts this object into Mega's internal model.
    pub fn convert_to_mega_model(self) -> MegaObjectModel {
        match self {
            GitObject::Commit(commit) => MegaObjectModel::Commit(commit.into()),
            GitObject::Tree(tree) => MegaObjectModel::Tree(tree.into()),
            GitObject::Blob(blob) => MegaObjectModel::Blob((&blob).into(), blob.into()),
            GitObject::Tag(tag) => MegaObjectModel::Tag(tag.into()),
        }
    }

    /// Converts this object into a standard Git model.
    pub fn convert_to_git_model(self) -> GitObjectModel {
        match self {
            GitObject::Commit(commit) => GitObjectModel::Commit(commit.into()),
            GitObject::Tree(tree) => GitObjectModel::Tree(tree.into()),
            GitObject::Blob(blob) => GitObjectModel::Blob((&blob).into(), blob.into()),
            GitObject::Tag(tag) => GitObjectModel::Tag(tag.into()),
        }
    }
}
