const SHIKI_SUPPORTED_LANGUAGES = new Set([
  'text',
  'txt',
  'plain',
  'plaintext',
  'ansi',

  'abap',
  'actionscript-3',
  'actionscript',
  'ada',
  'angular-html',
  'angular-ts',
  'apache',
  'apex',
  'apl',
  'applescript',
  'ara',
  'asciidoc',
  'adoc',
  'asm',
  'astro',
  'awk',

  'ballerina',
  'bash',
  'sh',
  'shell',
  'zsh',
  'bat',
  'batch',
  'beancount',
  'berry',
  'be',
  'bibtex',
  'bib',
  'bicep',
  'blade',
  'bsl',
  '1c',
  'c',
  'cadence',
  'cdc',
  'cairo',
  'clarity',
  'clojure',
  'clj',
  'cmake',
  'cobol',
  'codeowners',
  'codeql',
  'ql',
  'coffee',
  'coffeescript',
  'common-lisp',
  'lisp',
  'coq',
  'cpp',
  'c++',
  'crystal',
  'csharp',
  'c#',
  'cs',
  'css',
  'csv',
  'cue',
  'cypher',
  'cql',

  'd',
  'dart',
  'dax',
  'desktop',
  'diff',
  'docker',
  'dockerfile',
  'dotenv',
  'dream-maker',

  'edge',
  'elixir',
  'ex',
  'elm',
  'emacs-lisp',
  'elisp',
  'erb',
  'erlang',
  'erl',

  'fennel',
  'fish',
  'fluent',
  'ftl',
  'fortran-fixed-form',
  'f',
  'for',
  'f77',
  'fortran-free-form',
  'f90',
  'f95',
  'f03',
  'f08',
  'f18',
  'fsharp',
  'f#',
  'fs',
  'fsl',

  'gdresource',
  'gdscript',
  'gdshader',
  'genie',
  'gherkin',
  'git-commit',
  'git-rebase',
  'gleam',
  'glimmer-js',
  'gjs',
  'glimmer-ts',
  'gts',
  'glsl',
  'gnuplot',
  'go',
  'golang',
  'graphql',
  'gql',
  'groovy',
  'gsc',

  'hack',
  'haml',
  'handlebars',
  'hbs',
  'haskell',
  'hs',
  'haxe',
  'hcl',
  'hjson',
  'hlsl',
  'html',
  'html-derivative',
  'http',

  'hxml',
  'hy',
  'imba',
  'ini',
  'properties',

  'java',
  'javascript',
  'js',
  'jinja',
  'jison',
  'json',
  'json5',
  'jsonc',
  'jsonl',
  'jsonnet',
  'jssm',
  'jsx',
  'julia',
  'jl',
  'just',

  'kotlin',
  'kt',
  'kts',
  'kusto',
  'kql',

  'latex',
  'lean',
  'lean4',
  'less',
  'liquid',
  'log',
  'logo',
  'lua',
  'luau',
  'make',
  'makefile',
  'markdown',
  'md',
  'marko',
  'matlab',
  'mdc',
  'mdx',
  'mermaid',
  'mipsasm',
  'mojo',
  'move',
  'narrat',
  'nar',
  'nextflow',
  'nf',
  'nginx',
  'nim',
  'nix',
  'nushell',
  'nu',

  'objective-c',
  'objc',
  'objective-cpp',
  'ocaml',
  'ml',
  'pascal',
  'perl',
  'pl',
  'php',
  'plsql',
  'po',
  'pot',
  'potx',
  'postcss',
  'powerquery',
  'powershell',
  'ps',
  'ps1',
  'prisma',
  'prolog',
  'proto',
  'protobuf',
  'pug',
  'jade',
  'puppet',
  'purescript',
  'python',
  'py',

  'qml',
  'qmldir',
  'r',
  'racket',
  'rkt',
  'raku',
  'perl6',
  'razor',
  'reg',
  'regexp',
  'regex',
  'rel',
  'riscv',
  'rst',
  'ruby',
  'rb',
  'rust',
  'rs',

  'sas',
  'sass',
  'scala',
  'scheme',
  'scss',
  'sdbl',
  'shaderlab',
  'shader',
  'shellscript',
  'shellsession',
  'console',
  'smalltalk',
  'solidity',
  'sol',
  'soy',
  'sparql',
  'splunk',
  'spl',
  'sql',
  'ssh-config',
  'stata',
  'stylus',
  'styl',
  'svelte',
  'swift',
  'system-verilog',
  'systemd',

  'tasl',
  'tcl',
  'templ',
  'terraform',
  'tf',
  'tfvars',
  'tex',
  'toml',
  'ts-tags',
  'tsv',
  'tsx',
  'turtle',
  'twig',
  'typescript',
  'ts',
  'mts',
  'cts',
  'typespec',
  'tsp',
  'typst',
  'typ',

  'v',
  'vala',
  'vb',
  'vba',
  'cmd',
  'verilog',
  'vhdl',
  'viml',
  'vim',
  'vimscript',
  'vue',
  'vue-html',
  'vyper',
  'vy',

  'wasm',
  'wgsl',
  'wikitext',
  'mediawiki',
  'wiki',
  'wolfram',
  'wl',

  'xml',
  'xsl',

  'yaml',
  'yml',
  'zenscript',
  'zig',
  'zod'
])

const EXTENSION_TO_LANGUAGE: Record<string, string> = {
  '.js': 'javascript',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.jsx': 'jsx',
  '.ts': 'typescript',
  '.mts': 'typescript',
  '.cts': 'typescript',
  '.tsx': 'tsx',
  '.d.ts': 'typescript',

  '.html': 'html',
  '.htm': 'html',
  '.vue': 'vue',
  '.svelte': 'svelte',
  '.astro': 'astro',

  '.css': 'css',
  '.scss': 'scss',
  '.sass': 'sass',
  '.less': 'less',
  '.styl': 'stylus',
  '.stylus': 'stylus',
  '.postcss': 'postcss',

  '.json': 'json',
  '.json5': 'json5',
  '.jsonc': 'jsonc',
  '.jsonl': 'jsonl',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.toml': 'toml',
  '.xml': 'xml',
  '.xsl': 'xsl',
  '.svg': 'xml',
  '.csv': 'csv',
  '.tsv': 'tsv',
  '.ini': 'ini',

  '.c': 'c',
  '.h': 'c',
  '.cpp': 'cpp',
  '.cc': 'cpp',
  '.cxx': 'cpp',
  '.hpp': 'cpp',
  '.hxx': 'cpp',
  '.c++': 'cpp',
  '.h++': 'cpp',
  '.rs': 'rust',
  '.go': 'go',
  '.zig': 'zig',
  '.nim': 'nim',
  '.v': 'v',
  '.d': 'd',

  '.java': 'java',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.scala': 'scala',
  '.groovy': 'groovy',
  '.gradle': 'groovy',
  '.clj': 'clojure',
  '.cljs': 'clojure',
  '.cljc': 'clojure',
  '.edn': 'clojure',

  '.cs': 'csharp',
  '.csx': 'csharp',
  '.fs': 'fsharp',
  '.fsx': 'fsharp',
  '.fsi': 'fsharp',
  '.vb': 'vb',

  '.py': 'python',
  '.pyw': 'python',
  '.pyi': 'python',
  '.rb': 'ruby',
  '.erb': 'erb',
  '.php': 'php',
  '.lua': 'lua',
  '.luau': 'luau',
  '.pl': 'perl',
  '.pm': 'perl',
  '.r': 'r',
  '.R': 'r',
  '.jl': 'julia',

  '.hs': 'haskell',
  '.lhs': 'haskell',
  '.ml': 'ocaml',
  '.mli': 'ocaml',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.erl': 'erlang',
  '.hrl': 'erlang',
  '.elm': 'elm',
  '.purs': 'purescript',
  '.rkt': 'racket',
  '.scm': 'scheme',
  '.lisp': 'common-lisp',
  '.cl': 'common-lisp',

  '.swift': 'swift',
  '.m': 'objective-c',
  '.mm': 'objective-cpp',
  '.dart': 'dart',

  '.sh': 'bash',
  '.bash': 'bash',
  '.zsh': 'bash',
  '.fish': 'fish',
  '.ps1': 'powershell',
  '.psm1': 'powershell',
  '.psd1': 'powershell',
  '.bat': 'bat',
  '.cmd': 'bat',
  '.nu': 'nushell',

  '.env': 'dotenv',
  '.dockerfile': 'dockerfile',
  '.tf': 'terraform',
  '.tfvars': 'terraform',
  '.hcl': 'hcl',
  '.nix': 'nix',
  '.nginx': 'nginx',

  '.mk': 'make',
  '.make': 'make',
  '.mak': 'make',
  '.cmake': 'cmake',

  '.md': 'markdown',
  '.mdx': 'mdx',
  '.mdc': 'mdc',
  '.tex': 'latex',
  '.latex': 'latex',
  '.rst': 'rst',
  '.adoc': 'asciidoc',
  '.asciidoc': 'asciidoc',
  '.diff': 'diff',
  '.patch': 'diff',

  '.sql': 'sql',
  '.plsql': 'plsql',
  '.graphql': 'graphql',
  '.gql': 'graphql',
  '.prisma': 'prisma',
  '.cql': 'cypher',

  '.proto': 'proto',
  '.vim': 'viml',
  '.vimrc': 'viml',
  '.asm': 'asm',
  '.s': 'asm',
  '.wasm': 'wasm',
  '.sol': 'solidity',
  '.vy': 'vyper',
  '.wgsl': 'wgsl',
  '.glsl': 'glsl',
  '.hlsl': 'hlsl',
  '.mojo': 'mojo',
  '.move': 'move',
  '.cairo': 'cairo',
  '.just': 'just',
  '.http': 'http',
  '.hbs': 'handlebars',
  '.handlebars': 'handlebars',
  '.pug': 'pug',
  '.jade': 'pug',
  '.haml': 'haml',
  '.slim': 'ruby',
  '.liquid': 'liquid',
  '.twig': 'twig',
  '.jinja': 'jinja',
  '.jinja2': 'jinja',
  '.ejs': 'html',
  '.edge': 'edge',
  '.blade.php': 'blade',
  '.marko': 'marko',
  '.svx': 'mdx',
  '.typ': 'typst',
  '.typst': 'typst',

  '.rego': 'python',
  '.cedar': 'rust',
  '.polar': 'python',
  '.sentinel': 'python',

  '.htaccess': 'apache',
  '.properties': 'ini',
  '.conf': 'ini',
  '.cfg': 'ini',
  '.cnf': 'ini',
  '.editorconfig': 'ini',
  '.gitconfig': 'ini',
  '.gitmodules': 'ini',
  '.npmrc': 'ini',
  '.yarnrc': 'yaml',
  '.bowerrc': 'json',

  '.bzl': 'python',
  '.bazelrc': 'ini',
  '.bazelignore': 'text',
  '.bazelversion': 'text',
  '.bazelproject': 'yaml',
  '.buckconfig': 'ini',
  '.buckversion': 'text',

  '.txt': 'text',
  '.text': 'text',
  '.log': 'log',
  '.vtt': 'text',
  '.srt': 'text',
  '.ass': 'text',
  '.ssa': 'text',
  '.lrc': 'text',

  '.iml': 'xml',
  '.plist': 'xml',
  '.csproj': 'xml',
  '.fsproj': 'xml',
  '.vbproj': 'xml',
  '.vcxproj': 'xml',
  '.sln': 'ini',
  '.podspec': 'ruby',
  '.gemspec': 'ruby',
  '.rake': 'ruby',
  '.thor': 'ruby',
  '.cr': 'crystal',
  '.coffee': 'coffee',
  '.litcoffee': 'coffee',
  '.imba': 'imba',
  '.mint': 'typescript',
  '.reason': 'ocaml',
  '.res': 'ocaml',
  '.resi': 'ocaml',
  '.re': 'ocaml',
  '.rei': 'ocaml',
  '.hack': 'hack',
  '.hh': 'hack',
  '.hhi': 'hack'
}

const COMPOUND_EXTENSION_TO_LANGUAGE: Record<string, string> = {
  '.d.ts': 'typescript',
  '.d.mts': 'typescript',
  '.d.cts': 'typescript',

  '.spec.js': 'javascript',
  '.test.js': 'javascript',
  '.spec.ts': 'typescript',
  '.test.ts': 'typescript',
  '.spec.tsx': 'tsx',
  '.test.tsx': 'tsx',
  '.spec.jsx': 'jsx',
  '.test.jsx': 'jsx',

  '.config.js': 'javascript',
  '.config.mjs': 'javascript',
  '.config.cjs': 'javascript',
  '.config.ts': 'typescript',
  '.config.mts': 'typescript',
  '.config.cts': 'typescript',
  '.config.json': 'json',
  '.config.yaml': 'yaml',
  '.config.yml': 'yaml',
  '.config.toml': 'toml',

  '.blade.php': 'blade',

  '.env.local': 'dotenv',
  '.env.development': 'dotenv',
  '.env.production': 'dotenv',
  '.env.test': 'dotenv',
  '.env.example': 'dotenv'
}

const SPECIAL_FILE_TO_LANGUAGE: Record<string, string> = {
  dockerfile: 'dockerfile',
  'dockerfile.dev': 'dockerfile',
  'dockerfile.prod': 'dockerfile',
  'dockerfile.test': 'dockerfile',
  containerfile: 'dockerfile',

  makefile: 'make',
  gnumakefile: 'make',
  'makefile.am': 'make',
  'makefile.in': 'make',

  rakefile: 'ruby',
  gemfile: 'ruby',
  podfile: 'ruby',
  fastfile: 'ruby',
  appfile: 'ruby',
  matchfile: 'ruby',
  pluginfile: 'ruby',
  snapfile: 'ruby',
  vagrantfile: 'ruby',
  berksfile: 'ruby',
  cheffile: 'ruby',
  thorfile: 'ruby',
  guardfile: 'ruby',
  capfile: 'ruby',
  puppetfile: 'ruby',
  brewfile: 'ruby',
  appraisals: 'ruby',
  dangerfile: 'ruby',
  deliverfile: 'ruby',
  gymfile: 'ruby',
  scanfile: 'ruby',

  jenkinsfile: 'groovy',
  'build.gradle': 'groovy',
  'settings.gradle': 'groovy',

  buck: 'python',
  build: 'python',
  workspace: 'python',
  'build.bazel': 'python',
  'workspace.bazel': 'python',

  'cmakelists.txt': 'cmake',

  'package.json': 'json',
  'package-lock.json': 'json',
  'tsconfig.json': 'jsonc',
  'jsconfig.json': 'jsonc',
  'tslint.json': 'jsonc',
  '.eslintrc': 'json',
  '.eslintrc.json': 'json',
  '.prettierrc': 'json',
  '.prettierrc.json': 'json',
  '.babelrc': 'json',
  '.babelrc.json': 'json',
  '.swcrc': 'json',
  'composer.json': 'json',
  'bower.json': 'json',
  'lerna.json': 'json',
  'nx.json': 'json',
  'turbo.json': 'jsonc',
  'deno.json': 'jsonc',
  'deno.jsonc': 'jsonc',
  '.prettierrc.yaml': 'yaml',
  '.prettierrc.yml': 'yaml',

  '.travis.yml': 'yaml',
  '.gitlab-ci.yml': 'yaml',
  'docker-compose.yml': 'yaml',
  'docker-compose.yaml': 'yaml',
  'compose.yml': 'yaml',
  'compose.yaml': 'yaml',
  'pnpm-workspace.yaml': 'yaml',
  '.pre-commit-config.yaml': 'yaml',
  'mkdocs.yml': 'yaml',
  'pubspec.yaml': 'yaml',
  'pubspec.lock': 'yaml',
  'ansible.cfg': 'ini',

  'cargo.toml': 'toml',
  'cargo.lock': 'toml',
  'pyproject.toml': 'toml',
  'poetry.lock': 'toml',
  pipfile: 'toml',
  'gopkg.toml': 'toml',
  'gopkg.lock': 'toml',
  'netlify.toml': 'toml',
  'vercel.json': 'json',
  'fly.toml': 'toml',
  'wrangler.toml': 'toml',

  '.gitignore': 'text',
  '.gitattributes': 'text',
  '.mailmap': 'text',
  codeowners: 'codeowners',

  '.dockerignore': 'text',
  '.npmignore': 'text',
  '.slugignore': 'text',
  '.helmignore': 'text',
  '.gcloudignore': 'text',
  '.cfignore': 'text',
  '.env.example': 'dotenv',
  '.env.local': 'dotenv',
  '.env.development': 'dotenv',
  '.env.production': 'dotenv',
  '.env.test': 'dotenv',

  '.nvmrc': 'text',
  '.node-version': 'text',
  '.ruby-version': 'text',
  '.python-version': 'text',
  '.java-version': 'text',
  '.go-version': 'text',
  '.tool-versions': 'text',

  readme: 'markdown',
  'readme.md': 'markdown',
  'readme.txt': 'text',
  changelog: 'markdown',
  'changelog.md': 'markdown',
  history: 'markdown',
  'history.md': 'markdown',
  authors: 'text',
  contributors: 'text',
  license: 'text',
  licence: 'text',
  'license.md': 'markdown',
  'license.txt': 'text',
  copying: 'text',
  notice: 'text',
  patents: 'text',
  todo: 'markdown',
  'todo.md': 'markdown',

  procfile: 'yaml',
  'procfile.dev': 'yaml',
  justfile: 'just',
  '.htaccess': 'apache',
  '.htpasswd': 'text',
  'robots.txt': 'text',
  'humans.txt': 'text',
  'security.txt': 'text',
  'manifest.json': 'json',
  'site.webmanifest': 'json'
}

export function getLanguageForFile(fileName: string): string {
  if (!fileName) return 'text'

  const lowerFileName = fileName.toLowerCase()
  const baseName = lowerFileName.split('/').pop() || ''

  if (SPECIAL_FILE_TO_LANGUAGE[baseName]) {
    return SPECIAL_FILE_TO_LANGUAGE[baseName]
  }

  for (const [ext, lang] of Object.entries(COMPOUND_EXTENSION_TO_LANGUAGE)) {
    if (lowerFileName.endsWith(ext)) {
      return lang
    }
  }

  const ext = lowerFileName.match(/\.[^./\\]+$/)?.[0]

  if (ext && EXTENSION_TO_LANGUAGE[ext]) {
    return EXTENSION_TO_LANGUAGE[ext]
  }

  if (ext) {
    const langId = ext.slice(1)

    if (SHIKI_SUPPORTED_LANGUAGES.has(langId)) {
      return langId
    }
  }

  return 'text'
}
