[package]
name = "dagrs-derive"
authors = [
    "Quanyi Ma <eli@patch.sh>",
    "Xiaolong Fu <njufxl@gmail.com>",
    "Zhilei Qiu <qzl2503687@gmail.com>",
]
version = "0.4.2"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Dagrs follows the concept of Flow-based Programming and is suitable for the execution of multiple tasks with graph-like dependencies. Dagrs has the characteristics of high performance and asynchronous execution. It provides users with a convenient programming interface."
readme = "README.md"
repository = "https://github.com/dagrs-dev/dagrs"
keywords = ["DAG", "task", "async", "fbp", "tokio"]

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true

[features]
default = ["derive"]
derive = []
