//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "contributor_location")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub repository_id: Uuid,
    pub user_id: i32,
    pub is_from_china: bool,
    pub common_timezone: Option<String>,
    pub analyzed_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
