//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "build_targets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub task_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub path: Json,
    #[sea_orm(column_type = "Text")]
    pub target_state: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::orion_tasks::Entity",
        from = "Column::TaskId",
        to = "super::orion_tasks::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    OrionTasks,
}

impl Related<super::orion_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrionTasks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
