//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "orion_tasks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub changes: Json,
    pub repo_name: String,
    pub cl: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::build_events::Entity")]
    BuildEvents,
    #[sea_orm(has_many = "super::build_targets::Entity")]
    BuildTargets,
}

impl Related<super::build_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BuildEvents.def()
    }
}

impl Related<super::build_targets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BuildTargets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
