//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "target_state_histories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub build_target_id: Uuid,
    pub build_event_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub target_state: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::build_events::Entity",
        from = "Column::BuildEventId",
        to = "super::build_events::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BuildEvents,
    #[sea_orm(
        belongs_to = "super::build_targets::Entity",
        from = "Column::BuildTargetId",
        to = "super::build_targets::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BuildTargets,
}

impl Related<super::build_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BuildEvents.def()
    }
}

impl Related<super::build_targets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BuildTargets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
