[package]
name = "data_transporter"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { workspace = true }
repo_import = { workspace = true }
search = { workspace = true }
tudriver = { workspace = true }

# third-party (第三方依赖, 不写具体版本号, 具体版本只在根目录 Cargo.toml 中出现)
actix-multipart = "0.7"
actix-web = "4.10"
async-trait = "0.1"
chrono = { version = "0.4", features = ["clock"] }
futures-util = "0.3"
redis = "0.32"
sanitize-filename = "0.6"
semver = "1.0"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.44", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4"] }
tracing = "0.1"
utoipa = { version = "5.3", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "9.0", features = ["actix-web"] }
uuid = { version = "1.16", features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
] }
zip = "=2.4.2"
