//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "artifact_set_files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub set_id: i64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub path: String,
    pub oid: String,
    pub size_bytes: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub content_type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::artifact_objects::Entity",
        from = "Column::Oid",
        to = "super::artifact_objects::Column::Oid",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    ArtifactObjects,
    #[sea_orm(
        belongs_to = "super::artifact_sets::Entity",
        from = "Column::SetId",
        to = "super::artifact_sets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ArtifactSets,
}

impl Related<super::artifact_objects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtifactObjects.def()
    }
}

impl Related<super::artifact_sets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtifactSets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
