//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "artifact_sets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub repo: String,
    pub namespace: String,
    pub object_type: String,
    pub artifact_set_id: String,
    pub metadata: Option<Json>,
    pub created_by: Option<String>,
    pub created_at: DateTime,
    pub expires_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::artifact_set_files::Entity")]
    ArtifactSetFiles,
}

impl Related<super::artifact_set_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtifactSetFiles.def()
    }
}

impl Related<super::artifact_objects::Entity> for Entity {
    fn to() -> RelationDef {
        super::artifact_set_files::Relation::ArtifactObjects.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::artifact_set_files::Relation::ArtifactSets
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
