//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "artifact_objects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub oid: String,
    pub size_bytes: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub content_type: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub storage_key: String,
    pub created_at: DateTime,
    pub last_seen_at: DateTime,
    pub integrity: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::artifact_set_files::Entity")]
    ArtifactSetFiles,
}

impl Related<super::artifact_set_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtifactSetFiles.def()
    }
}

impl Related<super::artifact_sets::Entity> for Entity {
    fn to() -> RelationDef {
        super::artifact_set_files::Relation::ArtifactSets.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::artifact_set_files::Relation::ArtifactObjects
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
