//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::{BotStatusEnum, PermissionScopeEnum};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "bots")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub name: String,
    pub organization_id: Option<i64>,
    pub creator_user_id: i64,
    pub permission_scope: PermissionScopeEnum,
    pub status: BotStatusEnum,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bot_installations::Entity")]
    BotInstallations,
    #[sea_orm(has_many = "super::bot_tokens::Entity")]
    BotTokens,
}

impl Related<super::bot_installations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BotInstallations.def()
    }
}

impl Related<super::bot_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BotTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
