//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "buck_session")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub session_id: String,
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub repo_path: String,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub commit_message: Option<String>,
    pub from_hash: Option<String>,
    pub expires_at: DateTime,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::buck_session_file::Entity")]
    BuckSessionFile,
}

impl Related<super::buck_session_file::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BuckSessionFile.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
