//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "buck_session_file")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub session_id: String,
    #[sea_orm(column_type = "Text")]
    pub file_path: String,
    pub file_size: i64,
    pub file_hash: String,
    pub file_mode: Option<String>,
    pub upload_status: String,
    pub upload_reason: Option<String>,
    pub blob_id: Option<String>,
    pub uploaded_at: Option<DateTime>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::buck_session::Entity",
        from = "Column::SessionId",
        to = "super::buck_session::Column::SessionId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    BuckSession,
}

impl Related<super::buck_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BuckSession.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
