//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::{IntoActiveModel, entity::prelude::*};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "build_targets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub task_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub path: Json,
    #[sea_orm(column_type = "Text")]
    pub target_state: String, //latest state
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::orion_tasks::Entity",
        from = "Column::TaskId",
        to = "super::orion_tasks::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    OrionTasks,
}

impl Related<super::orion_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrionTasks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    pub fn create_default_target(id: Uuid, task_id: Uuid) -> Self {
        let default_path = "//";
        Self {
            id,
            task_id,
            path: serde_json::to_value(default_path).unwrap(),
            target_state: "default".to_string(),
        }
    }

    pub async fn insert_default_target(
        id: Uuid,
        task_id: Uuid,
        db: &impl ConnectionTrait,
    ) -> Result<String, DbErr> {
        let target = Self::create_default_target(id, task_id);
        let path = target.path.clone();
        target.into_active_model().insert(db).await?;
        Ok(path.to_string())
    }
}
//:path1 //:path2 //:path3

//target log:
//  - id
//  - target id
//  - task
//  - state
//  - createdAt
