//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "git_pr")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub number: i64,
    pub title: String,
    pub state: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub closed_at: Option<DateTime>,
    pub merged_at: Option<DateTime>,
    pub merge_commit_sha: Option<String>,
    pub repo_id: i64,
    pub sender_name: String,
    pub sender_id: i64,
    pub user_name: String,
    pub user_id: i64,
    pub commits_url: String,
    pub patch_url: String,
    pub head_label: String,
    pub head_ref: String,
    pub base_label: String,
    pub base_ref: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
