//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod db_enums;
pub mod git_blob;
pub mod git_commit;
pub mod git_issue;
pub mod git_pr;
pub mod git_repo;
pub mod git_tag;
pub mod git_tree;
pub mod lfs_locks;
pub mod lfs_objects;
pub mod mega_blob;
pub mod mega_commit;
pub mod mega_issue;
pub mod mega_mr;
pub mod mega_snapshot;
pub mod mega_tag;
pub mod mega_tree;
pub mod raw_blob;
pub mod refs;
