//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_group")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    pub description: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::mega_group_member::Entity")]
    MegaGroupMember,
    #[sea_orm(has_many = "super::mega_resource_permission::Entity")]
    MegaResourcePermission,
}

impl Related<super::mega_group_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MegaGroupMember.def()
    }
}

impl Related<super::mega_resource_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MegaResourcePermission.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
