//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_code_review_comment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub thread_id: i64,
    pub parent_id: Option<i64>,
    pub user_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::mega_code_review_thread::Entity",
        from = "Column::ThreadId",
        to = "super::mega_code_review_thread::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MegaCodeReviewThread,
}

impl Related<super::mega_code_review_thread::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MegaCodeReviewThread.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
