//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::MergeStatusEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_mr")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub link: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub merge_date: Option<DateTime>,
    pub status: MergeStatusEnum,
    #[sea_orm(column_type = "Text")]
    pub path: String,
    pub from_hash: String,
    pub to_hash: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub username: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
