//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_group_member")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub group_id: i64,
    pub username: String,
    pub joined_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::mega_group::Entity",
        from = "Column::GroupId",
        to = "super::mega_group::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MegaGroup,
}

impl Related<super::mega_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MegaGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
