//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "notification_event_types")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub code: String,
    pub category: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub system_required: bool,
    pub default_enabled: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::email_jobs::Entity")]
    EmailJobs,
    #[sea_orm(has_many = "super::user_notification_preferences::Entity")]
    UserNotificationPreferences,
}

impl Related<super::email_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmailJobs.def()
    }
}

impl Related<super::user_notification_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserNotificationPreferences.def()
    }
}

impl Related<super::user_notification_settings::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_notification_preferences::Relation::UserNotificationSettings.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::user_notification_preferences::Relation::NotificationEventTypes
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
