//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use core::task;

use api_model::buck2::{status::Status, types::ProjectRelativePath};
use sea_orm::{IntoActiveModel, entity::prelude::*, sqlx::Connection};
use serde::{Deserialize, Serialize};
use serde_json::to_value;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "orion_tasks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub changes: Json,
    pub repo_name: String,
    pub cl: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::build_events::Entity")]
    BuildEvents,
    #[sea_orm(has_many = "super::build_targets::Entity")]
    BuildTargets,
    #[sea_orm(has_many = "super::target_build_status::Entity")]
    TargetBuildStatus,
}

impl Related<super::build_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BuildEvents.def()
    }
}

impl Related<super::build_targets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BuildTargets.def()
    }
}

impl Related<super::target_build_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TargetBuildStatus.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    fn create_task(
        task_id: Uuid,
        cl_link: &str,
        repo: &str,
        changes: &Vec<Status<ProjectRelativePath>>,
    ) -> Result<Self, serde_json::Error> {
        Ok(Self {
            id: task_id,
            cl: cl_link.to_string(),
            repo_name: repo.to_string(),
            changes: to_value(changes)?,
            created_at: chrono::Utc::now().into(),
        })
    }

    pub async fn insert_task(
        task_id: Uuid,
        cl_link: &str,
        repo: &str,
        changes: &Vec<Status<ProjectRelativePath>>,
        db: &impl ConnectionTrait,
    ) -> Result<Model, DbErr> {
        let task_model = Self::create_task(task_id, cl_link, repo, changes)
            .map_err(|e| DbErr::Custom(e.to_string()))?;
        task_model.into_active_model().insert(db).await
    }
}
