//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use super::sea_orm_active_enums::StorageTypeEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "raw_blob")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub sha1: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub file_type: Option<String>,
    pub storage_type: StorageTypeEnum,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub data: Option<Vec<u8>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub local_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub remote_url: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
