//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "actor_type_enum")]
pub enum ActorTypeEnum {
    #[sea_orm(string_value = "human")]
    Human,
    #[sea_orm(string_value = "bot")]
    Bot,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "audit_action_enum")]
pub enum AuditActionEnum {
    #[sea_orm(string_value = "create_bot")]
    CreateBot,
    #[sea_orm(string_value = "update_bot")]
    UpdateBot,
    #[sea_orm(string_value = "delete_bot")]
    DeleteBot,
    #[sea_orm(string_value = "enable_bot")]
    EnableBot,
    #[sea_orm(string_value = "disable_bot")]
    DisableBot,
    #[sea_orm(string_value = "install_bot")]
    InstallBot,
    #[sea_orm(string_value = "uninstall_bot")]
    UninstallBot,
    #[sea_orm(string_value = "create_token")]
    CreateToken,
    #[sea_orm(string_value = "revoke_token")]
    RevokeToken,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "bot_status_enum")]
pub enum BotStatusEnum {
    #[sea_orm(string_value = "enabled")]
    Enabled,
    #[sea_orm(string_value = "disabled")]
    Disabled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "check_type_enum")]
pub enum CheckTypeEnum {
    #[sea_orm(string_value = "gpg_signature")]
    GpgSignature,
    #[sea_orm(string_value = "branch_protection")]
    BranchProtection,
    #[sea_orm(string_value = "commit_message")]
    CommitMessage,
    #[sea_orm(string_value = "cl_sync")]
    ClSync,
    #[sea_orm(string_value = "merge_conflict")]
    MergeConflict,
    #[sea_orm(string_value = "ci_status")]
    CiStatus,
    #[sea_orm(string_value = "code_review")]
    CodeReview,
    #[sea_orm(string_value = "cla_sign")]
    ClaSign,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "conv_type_enum")]
pub enum ConvTypeEnum {
    #[sea_orm(string_value = "comment")]
    Comment,
    #[sea_orm(string_value = "deploy")]
    Deploy,
    #[sea_orm(string_value = "commit")]
    Commit,
    #[sea_orm(string_value = "force_push")]
    ForcePush,
    #[sea_orm(string_value = "edit")]
    Edit,
    #[sea_orm(string_value = "review")]
    Review,
    #[sea_orm(string_value = "approve")]
    Approve,
    #[sea_orm(string_value = "merge_queue")]
    MergeQueue,
    #[sea_orm(string_value = "merged")]
    Merged,
    #[sea_orm(string_value = "closed")]
    Closed,
    #[sea_orm(string_value = "reopen")]
    Reopen,
    #[sea_orm(string_value = "label")]
    Label,
    #[sea_orm(string_value = "assignee")]
    Assignee,
    #[sea_orm(string_value = "mention")]
    Mention,
    #[sea_orm(string_value = "draft")]
    Draft,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "diff_side_enum")]
pub enum DiffSideEnum {
    #[sea_orm(string_value = "new")]
    New,
    #[sea_orm(string_value = "old")]
    Old,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "installation_bot_status_enum"
)]
pub enum InstallationBotStatusEnum {
    #[sea_orm(string_value = "enabled")]
    Enabled,
    #[sea_orm(string_value = "disabled")]
    Disabled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "installation_target_type_enum"
)]
pub enum InstallationTargetTypeEnum {
    #[sea_orm(string_value = "organization")]
    Organization,
    #[sea_orm(string_value = "repository")]
    Repository,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "merge_status_enum")]
pub enum MergeStatusEnum {
    #[sea_orm(string_value = "open")]
    Open,
    #[sea_orm(string_value = "merged")]
    Merged,
    #[sea_orm(string_value = "closed")]
    Closed,
    #[sea_orm(string_value = "draft")]
    Draft,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "orion_target_status_enum"
)]
pub enum OrionTargetStatusEnum {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "success")]
    Success,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "permission_enum")]
pub enum PermissionEnum {
    #[sea_orm(string_value = "read")]
    Read,
    #[sea_orm(string_value = "write")]
    Write,
    #[sea_orm(string_value = "admin")]
    Admin,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "permission_scope_enum"
)]
pub enum PermissionScopeEnum {
    #[sea_orm(string_value = "read")]
    Read,
    #[sea_orm(string_value = "write")]
    Write,
    #[sea_orm(string_value = "admin")]
    Admin,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "position_status_enum"
)]
pub enum PositionStatusEnum {
    #[sea_orm(string_value = "exact")]
    Exact,
    #[sea_orm(string_value = "shifted")]
    Shifted,
    #[sea_orm(string_value = "pending_reanchor")]
    PendingReanchor,
    #[sea_orm(string_value = "ambiguous")]
    Ambiguous,
    #[sea_orm(string_value = "not_found")]
    NotFound,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "queue_failure_type_enum"
)]
pub enum QueueFailureTypeEnum {
    #[sea_orm(string_value = "conflict")]
    Conflict,
    #[sea_orm(string_value = "test_failure")]
    TestFailure,
    #[sea_orm(string_value = "build_failure")]
    BuildFailure,
    #[sea_orm(string_value = "merge_failure")]
    MergeFailure,
    #[sea_orm(string_value = "system_error")]
    SystemError,
    #[sea_orm(string_value = "timeout")]
    Timeout,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "queue_status_enum")]
pub enum QueueStatusEnum {
    #[sea_orm(string_value = "waiting")]
    Waiting,
    #[sea_orm(string_value = "testing")]
    Testing,
    #[sea_orm(string_value = "merging")]
    Merging,
    #[sea_orm(string_value = "merged")]
    Merged,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ref_type_enum")]
pub enum RefTypeEnum {
    #[sea_orm(string_value = "branch")]
    Branch,
    #[sea_orm(string_value = "tag")]
    Tag,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "reference_type_enum"
)]
pub enum ReferenceTypeEnum {
    #[sea_orm(string_value = "mention")]
    Mention,
    #[sea_orm(string_value = "build_relates")]
    BuildRelates,
    #[sea_orm(string_value = "blocks")]
    Blocks,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "resource_type_enum")]
pub enum ResourceTypeEnum {
    #[sea_orm(string_value = "note")]
    Note,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "target_type_enum")]
pub enum TargetTypeEnum {
    #[sea_orm(string_value = "bot")]
    Bot,
    #[sea_orm(string_value = "bot_installation")]
    BotInstallation,
    #[sea_orm(string_value = "bot_token")]
    BotToken,
    #[sea_orm(string_value = "repository")]
    Repository,
    #[sea_orm(string_value = "organization")]
    Organization,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "thread_status_enum")]
pub enum ThreadStatusEnum {
    #[sea_orm(string_value = "resolved")]
    Resolved,
    #[sea_orm(string_value = "open")]
    Open,
}
