//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::OrionTargetStatusEnum;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "target_build_status")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub task_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub target_package: String,
    #[sea_orm(column_type = "Text")]
    pub target_name: String,
    #[sea_orm(column_type = "Text")]
    pub target_configuration: String,
    #[sea_orm(column_type = "Text")]
    pub category: String,
    #[sea_orm(column_type = "Text")]
    pub identifier: String,
    #[sea_orm(column_type = "Text")]
    pub action: String,
    pub status: OrionTargetStatusEnum,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::orion_tasks::Entity",
        from = "Column::TaskId",
        to = "super::orion_tasks::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    OrionTasks,
}

impl Related<super::orion_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrionTasks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
