//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tasks_refactor")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub changes: Json,
    pub repo_name: String,
    pub cl: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::build_events_refactor::Entity")]
    BuildEventsRefactor,
    #[sea_orm(has_many = "super::targets_refactor::Entity")]
    TargetsRefactor,
}

impl Related<super::build_events_refactor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BuildEventsRefactor.def()
    }
}

impl Related<super::targets_refactor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TargetsRefactor.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
