//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user_notification_preferences")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub username: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_type_code: String,
    pub enabled: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_notification_settings::Entity",
        from = "Column::Username",
        to = "super::user_notification_settings::Column::Username",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserNotificationSettings,

    #[sea_orm(
        belongs_to = "super::notification_event_types::Entity",
        from = "Column::EventTypeCode",
        to = "super::notification_event_types::Column::Code",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    NotificationEventTypes,
}

impl Related<super::user_notification_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserNotificationSettings.def()
    }
}

impl Related<super::notification_event_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationEventTypes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
