[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
# third-party (第三方依赖, 不写具体版本号, 具体版本只在根目录 Cargo.toml 中出现)
pgvector = { version = "0.4", features = ["postgres"] }
reqwest = { version = "0.12", features = ["json"] }
semver = "1.0"
serde = "1.0"
serde_json = "1.0"
tokio-postgres = "0.7"
