//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "locks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: String,
    pub data: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

/*
CREATE TABLE locks (
    id VARCHAR(200),
    data VARCHAR(10000),
    PRIMARY KEY (id)
);
 */
