//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "node")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub node_id: i64,
    pub git_id: String,
    pub mode: Vec<u8>,
    pub name: String,
    pub node_type: String,
    pub content_sha: Option<String>,
    pub data: Vec<u8>,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: chrono::NaiveDateTime,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: chrono::NaiveDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
