[package]
name = "neptune"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cmake = "0.1.50"
num_cpus = { workspace = true }

[dependencies]
libc = "0.2.155"
reqwest = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tokio-test = { workspace = true }

[features]
agent-ui = []
