[package]
name = "build-bazel-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.18.1"
tracing = "0.1.39"
url = "2.4.1"
