version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: orion-server/Dockerfile
    container_name: orion-server
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/orion
      - PORT=8004
      - BUILD_LOG_DIR=/tmp/buck2ctl
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orion
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata: