//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub mod prelude;

pub mod contributor_location;
pub mod crate_owners;
pub mod crate_users;
pub mod crates;
pub mod crates_info;
pub mod cves;
pub mod dependency_cache;
pub mod dependent_cache;
pub mod github_sync_status;
pub mod github_user;
pub mod graph_info;
pub mod license;
pub mod program_dependencies;
pub mod program_versions;
pub mod programs;
pub mod repo_sync_result;
pub mod repository_contributor;
pub mod rustsec_info;
pub mod rustsecs;
pub mod sea_orm_active_enums;
pub mod senseleak_res;
pub mod userloginfo;
pub mod version_info;
