//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "program_dependencies")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub name_and_version: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub dependency_name: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub dependency_version: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
