//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "rustsec_info")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub subtitle: String,
    #[sea_orm(column_type = "Text")]
    pub reported: String,
    #[sea_orm(column_type = "Text")]
    pub issued: String,
    #[sea_orm(column_type = "Text")]
    pub package: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "Text")]
    pub keywords: String,
    #[sea_orm(column_type = "Text")]
    pub aliases: String,
    #[sea_orm(column_type = "Text")]
    pub reference: String,
    #[sea_orm(column_type = "Text")]
    pub patched: String,
    #[sea_orm(column_type = "Text")]
    pub unaffected: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
