//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "crate_type_enum")]
pub enum CrateTypeEnum {
    #[sea_orm(string_value = "lib")]
    Lib,
    #[sea_orm(string_value = "application")]
    Application,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "sync_status_enum")]
pub enum SyncStatusEnum {
    #[sea_orm(string_value = "syncing")]
    Syncing,
    #[sea_orm(string_value = "succeed")]
    Succeed,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "analysing")]
    Analysing,
    #[sea_orm(string_value = "analysed")]
    Analysed,
}
