dagrs:
  node0:
    name: "node_0"
    after: []
    cmd: ""
  node1:
    name: "node_1"
    after: []
    cmd: ""
  node2:
    name: "node_2"
    after: []
    cmd: ""
  node3:
    name: "node_3"
    after: []
    cmd: ""
  node4:
    name: "node_4"
    after: []
    cmd: ""
  node5:
    name: "node_5"
    after: []
    cmd: ""
  node6:
    name: "node_6"
    after: []
    cmd: ""
  node7:
    name: "node_7"
    after: []
    cmd: ""
  node8:
    name: "node_8"
    after: []
    cmd: ""
  node9:
    name: "node_9"
    after: []
    cmd: ""
  root:
    name: "root"
    after: [
      "node0",
      "node1",
      "node2",
      "node3",
      "node4",
      "node5",
      "node6",
      "node7",
      "node8",
      "node9",
    ]
    cmd: ""