name = "Monobean"
product_name = "Monobean"
identifier = "org.Web3Infrastructure.Monobean"
category = "DeveloperTool"
formats = ["dmg"]
before-packaging-command = "bash fix_macos_deps.sh --refresh --output patched_dylibs --rpath @executable_path/../Frameworks ../target/release/monobean"
out_dir = "../target/build"
binaries_dir = "../target/release"
binaries = [{ path = "monobean", main = true }]
resources = [
  "../Monobean.gresource",
  "patched_dylibs/gdk-pixbuf-2.0/loaders/libpixbufloader-ani.so",
  "patched_dylibs/gdk-pixbuf-2.0/loaders/libpixbufloader-bmp.so",
  "patched_dylibs/gdk-pixbuf-2.0/loaders/libpixbufloader-gif.so",
  "patched_dylibs/gdk-pixbuf-2.0/loaders/libpixbufloader-icns.so",
  "patched_dylibs/gdk-pixbuf-2.0/loaders/libpixbufloader-ico.so",
  "patched_dylibs/gdk-pixbuf-2.0/loaders/libpixbufloader-pnm.so",
  "patched_dylibs/gdk-pixbuf-2.0/loaders/libpixbufloader-qtif.so",
  "patched_dylibs/gdk-pixbuf-2.0/loaders/libpixbufloader-tga.so",
  "patched_dylibs/gdk-pixbuf-2.0/loaders/libpixbufloader-tiff.so",
  "patched_dylibs/gdk-pixbuf-2.0/loaders/libpixbufloader-xbm.so",
  "patched_dylibs/gdk-pixbuf-2.0/loaders/libpixbufloader-xpm.so",
]
icons = [
  "icons/scalable/apps/mono-white-logo.ico",
  "icons/scalable/apps/mono-black-logo.ico",
]
authors = ["Neon <neonkk@qq.com>"]
description = "Monobean is a simple and easy-to-use GUI, built with GTK4 and Rust. It provides a user-friendly interface for managing your monorepo code."

[macos]
frameworks = [
  "patched_dylibs/libadwaita-1.0.dylib",
  "patched_dylibs/libappstream.5.dylib",
  "patched_dylibs/libcairo-gobject.2.dylib",
  "patched_dylibs/libcairo-script-interpreter.2.dylib",
  "patched_dylibs/libcairo.2.dylib",
  "patched_dylibs/libcrypto.3.dylib",
  "patched_dylibs/libepoxy.0.dylib",
  "patched_dylibs/libfontconfig.1.dylib",
  "patched_dylibs/libfreetype.6.dylib",
  "patched_dylibs/libfribidi.0.dylib",
  "patched_dylibs/libgdk_pixbuf-2.0.0.dylib",
  "patched_dylibs/libgio-2.0.0.dylib",
  "patched_dylibs/libglib-2.0.0.dylib",
  "patched_dylibs/libgmodule-2.0.0.dylib",
  "patched_dylibs/libgobject-2.0.0.dylib",
  "patched_dylibs/libgraphene-1.0.0.dylib",
  "patched_dylibs/libgraphite2.3.2.1.dylib",
  "patched_dylibs/libgtk-4.1.dylib",
  "patched_dylibs/libgtksourceview-5.0.dylib",
  "patched_dylibs/libharfbuzz-subset.0.dylib",
  "patched_dylibs/libharfbuzz.0.dylib",
  "patched_dylibs/libintl.8.dylib",
  "patched_dylibs/libjpeg.8.3.2.dylib",
  "patched_dylibs/liblzma.5.dylib",
  "patched_dylibs/liblzo2.2.dylib",
  "patched_dylibs/libpango-1.0.0.dylib",
  "patched_dylibs/libpangocairo-1.0.0.dylib",
  "patched_dylibs/libpangoft2-1.0.0.dylib",
  "patched_dylibs/libpcre2-8.0.dylib",
  "patched_dylibs/libpixman-1.0.dylib",
  "patched_dylibs/libpng16.16.dylib",
  "patched_dylibs/libssl.3.dylib",
  "patched_dylibs/libtiff.6.dylib",
  "patched_dylibs/libX11.6.dylib",
  "patched_dylibs/libXau.6.dylib",
  "patched_dylibs/libxcb-render.0.0.0.dylib",
  "patched_dylibs/libxcb-shm.0.0.0.dylib",
  "patched_dylibs/libxcb.1.1.0.dylib",
  "patched_dylibs/libXdmcp.6.dylib",
  "patched_dylibs/libXext.6.dylib",
  "patched_dylibs/libxmlb.2.dylib",
  "patched_dylibs/libXrender.1.dylib",
  "patched_dylibs/libyaml-0.2.dylib",
  "patched_dylibs/libzstd.1.5.7.dylib"
]

[dmg]
background = "icons/scalable/apps/mono-white-logo.ico"
