[package]
name = "import_tugraph"
version = "0.1.0"
edition = "2021"
default-run = "import_tugraph"

[[bin]]
name = "import_tugraph"
path = "src/main.rs"


[dependencies]
model = { workspace = true }
repo_import = { workspace = true }

# third-party (第三方依赖, 不写具体版本号, 具体版本只在根目录 Cargo.toml 中出现)
dotenvy = "0.15"
futures = "0.3"
futures-util = "0.3"
neo4rs = "0.8"
rdkafka = { version = "0.37", features = ["cmake-build"] }
serde_json = "1.0"
structopt = "0.3"
tokio = { version = "1.44", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
serial_test = "0.5"