apiVersion: apps/v1
kind: Deployment
metadata:
  name: import-tugraph
  namespace: crates-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: import-tugraph
  template:
    metadata:
      labels:
        app: import-tugraph
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: container-0
        image: localhost:30500/cratespro-import-tugraph:local-20250903-0740
        imagePullPolicy: IfNotPresent
        env:
        - name: MEGA_BASE_URL
          value: "http://git.gitmega.nju:8000"
        # - name: KAFKA_CONSUMER_GROUP_ID
        #   value: "instance-test1-import-tugraph-group"
        - name: POSTGRES_HOST_IP
          value: "postgresql-test1.postgresql.svc.cluster.local"
        - name: POSTGRES_HOST_PORT
          value: "5432"
        - name: TUGRAPH_BOLT_URL
          value: "bolt://tugraph-test1.tugraph.svc.cluster.local:7687"
        - name: LGRAPH_IMPORT_PATH
          value: "/usr/local/bin/lgraph_import"
        - name: LGRAPH_CONFIG_PATH
          value: "/workdir/import.config"
        - name: LGRAPH_DB_DIR
          value: "/var/lgraph_db"
        volumeMounts:
        - name: output-volume
          mountPath: /workdir/target
        - name: lgraph-db-volume
          mountPath: /var/lgraph_db
      volumes:
      - name: output-volume
        hostPath:
          path: /mnt/devops/instances/test1/cratespro-backend/output
          type: Directory
      - name: lgraph-db-volume
        hostPath:
          path: /home/rust/tugraph/lgraph_db
          type: Directory
