# the directory where the data files is located, such as logs, database, etc.
# can be overrided by environment variable `MEGA_BASE_DIR`
base_dir = "/tmp/.mono"

# Filling the following environment variables with values you set
## Logging Configuration
[log]
# The path which log file is saved
log_path = "${base_dir}/logs"

# log level
level = "debug"

# print std log in console, disable it on production for performance
print_std = true


[database]
# "sqlite" | "postgres"
# "sqlite" will use `db_path` and ignore `db_url`
db_type = "postgres"

# used for sqlite
db_path = "${base_dir}/mega.db"

# database connection url
db_url = "postgres://mono:mono@mono-pg:5432/mono"

# db max connection, setting it to twice the number of CPU cores would be appropriate.
max_connection = 16

# db min connection, setting it to the number of CPU cores would be appropriate.
min_connection = 8

# Whether to disabling SQLx Log
sqlx_logging = false


[storage]

obs_access_key = ""
obs_secret_key = ""

# cloud storage region
obs_region = "cn-east-3"

# Override the endpoint URL used for remote storage services
obs_endpoint = "https://obs.cn-east-3.myhuaweicloud.com"


[monorepo]
## Only import directory support multi-branch commit and tag, monorepo only support main branch
## Mega treats files under this directory as import repo and other directories as monorepo
import_dir = "/third-part"

disable_http_push = false

[pack]
# The maximum memory used by decode, Unit is GB
pack_decode_mem_size = 4

# The location where the object stored when the memory used by decode exceeds the limit
pack_decode_cache_path = "${base_dir}/cache"

clean_cache_after_decode = true

# The maximum meesage size in channel buffer while decode
channel_message_size = 1_000_000

# Maximum pack size, unit GB, enforces to use LFS off the limit
maximum_pack_size = 1


[lfs]
# LFS Server url
url = "https://git.gitmono.com"

# set the local path of the lfs storage
lfs_obj_local_path = "${base_dir}/lfs"

## IMPORTANT: The 'enable_split' feature can only be enabled for new databases. Existing databases do not support this feature.
# Enable or disable splitting large files into smaller chunks
enable_split = true  # Default is disabled. Set to true to enable file splitting.

# Size of each file chunk when splitting is enabled, in bytes. Ignored if splitting is disabled.
split_size = 20971520 # Default size is 20MB (20971520 bytes)

[oauth]
# GitHub OAuth application client id and secret
github_client_id = ""
github_client_secret = ""

# Used redirect to ui after login
ui_domain = "https://console.gitmono.com"

# Set .gitmono.com on Production
cookie_domain = ".gitmono.com"