[package]
name = "mega"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = 'src/mega.rs'

[dependencies]
gpui.workspace = true
settings.workspace = true
reqwest_client.workspace = true

futures.workspace = true
serde.workspace = true
serde_json.workspace = true
bytes.workspace = true
schemars.workspace = true
anyhow.workspace = true
radix_trie.workspace = true
log.workspace = true
