name: "Build openssl interop container from master"

on:
  schedule:
    - cron:  '20 0 * * *'
  workflow_dispatch:

jobs:
  update_quay_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
         fetch-depth: 0
      - name: "log in to quay.io"
        run: |
          docker login -u openssl-ci+machine -p ${{ secrets.QUAY_IO_PASSWORD }} quay.io
      - name: "Build container"
        run: |
          cd test/quic-openssl-docker/
          docker build -t quay.io/openssl-ci/openssl-quic-interop:latest .
      - name: "Push to quay"
        run: |
          docker push quay.io/openssl-ci/openssl-quic-interop:latest

