rust_binary(
    name = "explicit_main",
    srcs = [
        "src/main.rs",
    ],
    crate_root = "src/main.rs",
    edition = "2024",
)

rust_library(
    name = "globbed_lib",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    visibility = [
        "PUBLIC",
    ],
)
