[package]
name = "mega-app"
version = "0.1.0"
description = "A distributed Git Application"
authors = ["Quanyi Ma <genedna@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/web3infra-foundation/mega"
edition = "2021"
rust-version = "1.81.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tauri = { version = "2.0.2", features = [] }
tokio = { workspace = true }
home = { workspace = true }
tauri-plugin-fs = "2.0.1"
tauri-plugin-shell = "2.0.1"

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
