load("@prelude//rust:cargo_package.bzl", "cargo")

filegroup(
    name = "getcveid-0.1.0.crate",
    srcs = [
        "src/kafka_handler.rs",
        "src/main.rs",
    ],
)

pkg_deps = [
    "//third-party:dotenvy",
    "//third-party:rdkafka",
    "//third-party:reqwest",
    "//third-party:scraper",
    "//third-party:serde",
    "//third-party:serde_json",
    "//third-party:tokio",
    "//third-party:tokio-postgres",
    "//third-party:tracing",
    "//third-party:tracing-subscriber",
]

cargo.rust_binary(
    name = "getcveid",
    srcs = [":getcveid-0.1.0.crate"],
    crate_root = "getcveid-0.1.0.crate/src/main.rs",
    edition = "2024",
    deps = pkg_deps,
    visibility = ["PUBLIC"],
)
