apiVersion: batch/v1
kind: CronJob
metadata:
  name: getcveid
  namespace: crates-pro
spec:
  schedule: "0 * * * *"  # Run once per hour at minute 0
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: getcveid
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          containers:
          - name: container-0
            image: localhost:30500/crates-pro-getcveid:local-20251024-2147
            imagePullPolicy: IfNotPresent
            env:
            - name: POSTGRES_HOST_IP
              value: "postgresql-test1.postgresql.svc.cluster.local"
            - name: POSTGRES_HOST_PORT
              value: "5432"
            - name: KAFKA_BROKER
              value: "kafka.confluent.svc.cluster.local:9092"
            volumeMounts:
            - name: log-volume
              mountPath: /workdir/log
          volumes:
          - name: log-volume
            hostPath:
              path: /mnt/devops/log/getcveid
              type: DirectoryOrCreate
