//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "node")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub node_id: i64,
    pub git_id: String,
    pub last_commit: String,
    pub node_type: String,
    pub name: Option<String>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))")]
    pub mode: Vec<u8>,
    pub content_sha: Option<String>,
    pub size: i32,
    pub repo_path: String,
    pub full_path: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
