url = "http://localhost:8000"
mount_path = "/home/luxian/megadir/mount"
store_path = "/home/luxian/megadir/store"

[[works]]
path = "third-part/mega/libra"
node = 26
hash = "4b825dc642cb6eb9a060e54bf8d69288fbee4904"

[[works]]
path = "third-part/mega/scorpio"
node = 17
hash = "4b825dc642cb6eb9a060e54bf8d69288fbee4904"
