[package]
name = "repo_import"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
model = { workspace = true }

# third-party (第三方依赖, 不写具体版本号, 具体版本只在根目录 Cargo.toml 中出现)
bincode = "1.3"
cargo_metadata = "0.18"
csv = "1.3"
dotenvy = "0.15"
futures = "0.3"
git2 = "0.20"
lazy_static = "1.5"
log = "0.4"
once_cell = "1.21"
pretty_env_logger = "0.5"
rayon = "1.10"
rdkafka = { version = "0.37", features = ["cmake-build"] }
semver = "1.0"
serde = "1.0"
serde_json = "1.0"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres"] }
ssh2 = "0.9"
tempfile = "3.19"
tokio = { version = "1.44", features = ["full"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2.5"
uuid = { version = "1.16", features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
] }
walkdir = "2.5"

[dev-dependencies]
# 开发依赖可以不写在根目录 Cargo.toml 中
mockall = "0.13"
