[package]
edition = "2021"
name = "tudriver"
version = "0.1.0"

[dependencies]
# third-party (第三方依赖, 不写具体版本号, 具体版本只在根目录 Cargo.toml 中出现)
base64 = "0.22"
dotenvy = "0.15"
neo4rs = "0.8"
serde_json = "1.0"
tokio = { version = "1.44", features = ["full"] }
tracing = "0.1"
