//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod commit;
pub mod objects;
pub mod locks;
pub mod meta;
pub mod mr;
pub mod mr_info;
pub mod node;
pub mod refs;
pub mod issue;
pub mod repo_directory;
pub mod pull_request;
pub mod model;
