//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::{entity::prelude::*, ActiveValue::NotSet, Set};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Hash)]
#[sea_orm(table_name = "repo_directory")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pid: i32,
    pub name: String,
    pub is_repo: bool,
    pub full_path: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

pub fn new(pid: i32, name: &str, full_path: &str) -> ActiveModel {
    self::ActiveModel {
        id: NotSet,
        pid: Set(pid),
        name: Set(name.to_owned()),
        is_repo: Set(false),
        full_path: Set(full_path.to_owned()),
        created_at: Set(chrono::Utc::now().naive_utc()),
        updated_at: Set(chrono::Utc::now().naive_utc()),
    }
}
