[package]
name = "atlas"
version = "0.1.0"
edition = "2021"

[dependencies]
async-openai = "0.24.0"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros"] }
