name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            arch: x86_64
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            arch: aarch64
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            arch: x86_64
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true

      - name: Install system dependencies
        uses: ./.github/install-dep
        with:
          cache-key: sysdeps
          platform: ${{ matrix.os }}

      - name: Build libra
        run: |
          cargo build --release --target ${{ matrix.target }} --manifest-path libra/Cargo.toml

      - name: Package monobean
        shell: bash
        run: |
          cargo packager --release --manifest-path monobean/Cargo.toml --target ${{ matrix.target }} --config monobean/resources/packager_${{ matrix.target}}.toml

      - name: Prepare Linux
        if: startsWith(github.ref, 'refs/tags/v') && contains(matrix.os, 'ubuntu')
        run: |
          makepkg target/build/
          mv target/release/libra ${{ github.workspace }}/libra_${{ github.ref_name }}_${{ matrix.target }}
          mv target/build/Monobean__${{ matrix.arch }}.tar.gz.zst ${{ github.workspace }}/Monobean_${{ github.ref_name }}_${{ matrix.target }}.tar.gz.zst
          mv target/build/Monobean__${{ matrix.arch }}.deb ${{ github.workspace }}/Monobean_${{ github.ref_name }}_${{ matrix.target }}.deb
      
      - name: Prepare Windows
        if: startsWith(github.ref, 'refs/tags/v') && contains(matrix.os, 'windows')
        run: |
          mv target/release/libra.exe ${{ github.workspace }}/libra_${{ github.ref_name }}_${{ matrix.target }}.exe
          mv target/build/Monobean__${{ matrix.arch }}.exe ${{ github.workspace }}/Monobean_${{ github.ref_name }}_${{ matrix.target }}.exe

      - name: Prepare MacOS
        if: startsWith(github.ref, 'refs/tags/v') && contains(matrix.os, 'macos')
        run: |
          mv target/release/libra ${{ github.workspace }}/libra_${{ github.ref_name }}_${{ matrix.target }}
          mv target/build/Monobean__${{ matrix.arch }}.dmg ${{ github.workspace }}/Monobean_${{ github.ref_name }}_${{ matrix.target }}.dmg
      
      - name: Release Linux
        if: startsWith(github.ref, 'refs/tags/v') && contains(matrix.os, 'ubuntu')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            libra_${{ github.ref_name }}_${{ matrix.target }}
            Monobean_${{ github.ref_name }}_${{ matrix.target }}.tar.gz.zst
            Monobean_${{ github.ref_name }}_${{ matrix.target }}.deb

      - name: Release Windows
        if: startsWith(github.ref, 'refs/tags/v') && contains(matrix.os, 'windows')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            libra_${{ github.ref_name }}_${{ matrix.target }}.exe
            Monobean-${{ github.ref_name }}-${{ matrix.target }}.exe

      - name: Release MacOS
        if: startsWith(github.ref, 'refs/tags/v') && contains(matrix.os, 'macos')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            libra_${{ github.ref_name }}_${{ matrix.target }}
            Monobean_${{ github.ref_name }}_${{ matrix.target }}.dmg