name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: mono-engine
            context: .
            dockerfile: mono/Dockerfile

          - name: ui
            context: moon
            dockerfile: moon/apps/web/Dockerfile

          - name: orion-server
            context: .
            dockerfile: orion-server/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Tag
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ steps.tag.outputs.TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:latest
  create-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Generate Release Notes
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          sed "s/\${VERSION}/$VERSION/g" .github/release-template.md > release.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release.md
          overwrite_files: true
