name: Rust Extensions Check, Test and Lints

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/rust-**'
      - 'extensions/rust/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  clippy:
    name: Clippy Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: extensions/rust
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run cargo clippy
        run: |
          cargo build
          cargo clippy --all-targets --all-features --no-deps -- -D warnings

  test:
    name: Full Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true

      - name: Run cargo test
        run: |
          cargo test --manifest-path extensions/rust/Cargo.toml --all-features --no-fail-fast -- --nocapture